const VALUES = {
  'PLACE-NAME': undefined,
  'PLACE-ID': undefined,
  SSID: undefined,
  'VPN-PASSPHRASE': undefined,
  'VPN-USER': undefined,
  'VPN-PASSWORD': undefined,
  'PUBLIC-IP': undefined,
  'ISP-GATEWAY': undefined,
  'ISP1-GATEWAY': undefined,
  'ISP2-GATEWAY': undefined,
  'ISP1-ADDRESS': undefined,
  'ISP2-ADDRESS': undefined,
  'MAC-AP1': undefined,
  'MAC-AP2': undefined,
};
